services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  db-admin:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5433:8080"
    volumes:
      - db-data:/pgadmin4/servers.json

volumes:
    db-data:
