CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--;;

CREATE TABLE IF NOT EXISTS WALLET (
  id uuid UNIQUE NOT NULL PRIMARY KEY,
  btc_amount NUMERIC NOT NULL,
  usd_amount_at NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
